### PR TITLE
various small fixes

### PR DESCRIPTION
**Pull request by itoffshore**
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/83#issuecomment-330304279
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/89#issuecomment-330321557
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/97

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore but now getting errors in Travis 

```./setup-ngxblocker: line 191: syntax error near unexpected token `)'

./setup-ngxblocker: line 191: `		 last) grep -nE "^[ ]+$find_str" $file | tail -n1 | awk -F: '{print $1}''```

See build log > https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/277671916

**Comment by mitchellkrogza** [comment]
Reverted with Patch for now to previous versions > https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/595681409473850eadfb6cf2da38f7b79bbb4ab8

**Comment by mitchellkrogza** [comment]
@itoffshore There's a lot of bugs in Travis that have been ongoing now for about 2 months+. Builds that fail show as passed in the Commit History and also on Travis CI until you actually click into the actual Travis build and then you can see it failed. Have reported this to them a number of times now but they cannot seem to fix it. 

screen shot 2017-09-20 at 2 06 15 pm

screen shot 2017-09-20 at 12 25 27 pm
screen shot 2017-09-20 at 12 25 43 pm

**Comment by itoffshore** [comment]
I see the problem & will make a new `PR`

**Comment by mitchellkrogza** [comment]
Thanks so much @itoffshore

**Pull request merged**
