### PR TITLE
fix dash shell compatibilities install / setup-ngxblocker

### PR DESCRIPTION
**Pull request by itoffshore**
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/39

also fixes a small spacing bug in `setup-ngxblocker => nginx.conf`

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thank you Stuart @itoffshore

**Comment by mitchellkrogza** [comment]
@itoffshore just tested setup script this morning, it should only add the following 2 includes into a .vhost file 

blockbots.conf
ddos.conf

all the other includes are already done within globalblacklist.conf on lines 212, 746, 820, 831, 4815, 4957 and 4972

**Comment by mitchellkrogza** [comment]
@itoffshore  please also check setup-ngxblocker as it adds

```
include /etc/nginx/conf.d/globalblacklist.conf;
include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
```

into /etc/nginx/nginx.conf

but it should rather check if the line

`include /etc/nginx/conf.d/*; `

exists and if not just add that one line and not the two includes individually as it causes the files to be loaded twice due to the existence of the default nginx config line `include /etc/nginx/conf.d/*;`  

Thereafter adding the two includes again causes an **EMERG "server_names_hash_bucket_size" directive is duplicate**, commenting out `include /etc/nginx/conf.d/globalblacklist.conf;` and then another nginx -t gives a further EMERG due to the globalblacklist.conf being loaded twice **bot2_connlimit is already bound to key $bot_iplimit**

**Comment by mitchellkrogza** [comment]
Also running setup-ngblocker twice or more causes duplicate IP's to be whitelisted in whitelist-ips.conf, should first check if the ip to be whitelisted already exists in whitelist-ips.conf.

screen shot 2017-04-28 at 1 27 36 pm

**Comment by itoffshore** [comment]
ok have fixed all the above - will make a `PR` shortly:

```
Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

WARN:      /etc/nginx/bots.d/* detected               => /etc/nginx/sites-available/test.vhost
INFO:      /etc/nginx/conf.d/* detected               => /etc/nginx/nginx.conf
```

**Comment by mitchellkrogza** [comment]
Confirmed fixed, tested and working 100% in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/45

**Pull request merged**
