### PR TITLE
add freebsd compatibility

### PR DESCRIPTION
**Pull request by netchild**
The big picure is:
 - set some variables based upon OS name
 - use suitable commands based upon OS name (e.g. "sed" or "gsed", and "pidof" or "pgrep")
 - if "dig" is not found, skip IP part instead of failing
 - inform how to install a dependency on FreeBSD
 - in some cases I wrap the setting of variables into a function, this is to be able to use find_binary (via the function wrapper, the find_binary function is already defined at run-time, without the wrapper it isn't)

### CODE REVIEW

**Comment by netchild** [comment]
- I'm new to git. I've seen the merge conflict (because of the change for dig). I resolved this in my branch. Then I went back to this pull request and noticed that it recorded my 2nd commit in the line "Merge branch 'master' into FreeBSD 110fc5a" on this page. This gave me the impression that it automatically picked up my changes to my branch in here (and only after that the CI system was starting its work). What I've read in a google search suggests that my understanding is correct. If there was no other commit to the 3 files I modified (only to other files), then it should be OK (I assume github is using the diff of my master branch vs. my feature branch, and not the diff between the upstream master branch and my feature branch). Currently my master branch tells me "This branch is even with mitchellkrogza:master." and that the feature branch is 2 commits ahead (but nothing behind). Am I overlooking something?
- renamed as suggested
- dig: in my patch it is doing the same, the difference in my patch is that I use the result of find_binary to call dig, if you don't like that just tell me and I remove this part
- $OS is global in only one script, in the other two scripts it is local. I agree that I can move it in one file to a global place to not have to do it in two places. Do you want to have it global in the 3rd script as well?
- $SED_CMD: I will move it.

**Comment by netchild** [comment]
As you consider the variables in the beginning as user serviceable parts, what about making them settable from the environment instead of "edit file by hand" and have it overwritten on next update? Something like this:
---snip---
: ${CONF_DIR:="/etc/nginx/conf.d"}
---snip---

This way it is set to /etc/nginx/conf.d if it is not set in the environment of the shell and the user doesn't need to modify the files and saves some typing (not using the command line options).

**Comment by itoffshore** [comment]
I think the easiest way to make a clean `PR` is to copy your locally changed files somewhere & then delete & re-create your `local` branch (`git checkout -b mybranch`).

you can then copy the local files you were working on back over the new `local` branch

when I'm working on a branch I find it useful to run `git diff` before making a commit

finally you can **force overwrite (+)** your `remote` branch with the `local` changes as shown in my [rebasing notes](https://it-offshore.co.uk/code/81-alpine-linux-pull-requests-on-github) - `git push -u origin +mybranch`

I don't think we need to set `default` variable values with shell substitution (in normal operation only the globalblacklist is updated)  I do think the USER configurable / `default` values should be split out to a separate file & sourced by the helper scripts - this would allow the helper scripts to also be versioned & updated (but this should be a separate PR or commit)

**Comment by netchild** [comment]
I can have a look at this force overwrite, but I do not understand the "why"... If I click in this pull request on the "files changed" tab, I see the clean result of _all_ commits, not only my first request. So the changes I made based upon your review are in. Again, my repo does not show any missing changes from the upstream repo, all of them are incorporated.
What is the meaning of "clean" in this regard? What am I missing?

**Comment by itoffshore** [comment]
At the moment this PR has 5 commits instead of one. Yes it looks ok in the files changed tab - but what about in the future if someone is looking back at the changes applied ? What if someone is viewing the changes in a terminal git ? Then there are various commits some reversing each other when instead the commits could have been squashed into one with the `fixup` functionality builtin to `git`which I am [indicating to you for a 3rd time](https://it-offshore.co.uk/code/81-alpine-linux-pull-requests-on-github):

`git rebase -i FreeBSD~5`

change the top 4 commits to type `fixup` & the last commit to `reword` for a comprehensive commit message. The 5 commits will all be squashed into one commit & you will have the opportunity to make a single commit message describing the changes for FreeBSD.

finally force overwrite the PR

`git push -u origin +FreeBSD`

this is a clean PR & much clearer

**Comment by itoffshore** [comment]
I also think FreeBSd users should install `psmisc` to give them `pidof`

there are [differences between `pidof` &` pgrep`](https://unix.stackexchange.com/questions/351765/what-is-the-difference-between-pidof-and-pgrep)

**Comment by netchild** [comment]
Thanks for explaining me the "why" (I prefer to understand what I do). I tried hard to workaround the deficiencies in git you described. In the beginning it gave me a lot of merge conflicts for files I didn't touch in my changes. What worked for me -- sort of -- in the end was to only use my own commits  (via reword/fixup) and to drop what came from upstream. Afterwards I made a merge from origin/master to get those objects into my branch. I have no idea if what is there now is ok or not (so clearly, I don't understand what git is doing behind the scenes). Can you please check and advise how to fix this it is not as required?

Regarding your comment about pidof/pgrep: in the use case here it is working and compatible. In general it is different. For this particular case I do not want to ask FreeBSD users to install pidof (the FreeBSD way of doing what the script wants to do would be "service nginx status" and "service nginx reload"). If you do not like to use the in-this-case-compatible pgrep, I can remove this part from the patch and when I add a package for this to the FreeBSD package system (I'm one of the FreeBSD developers), I add a local patch for this there (the generic goal is that patches are upstreamed so that we don't have to have local patches).

**Comment by itoffshore** [comment]
This is why `pidof` should be used in FreeBSD & not `pgrep`

```
$ ps ax | grep '[w]atch'
   12 ?        S      0:04 [watchdog/0]
   15 ?        S      0:04 [watchdog/1]
   33 ?        S<     0:00 [watchdogd]
18451 pts/5    S+     0:02 watch -n600 tail log-file
$ pgrep watch
12
15
33
18451
$ pidof watch
18451
```
you still need to tidy up this `PR` - it is `4` commits instead of `1`. As previously mentioned above if you are having trouble with `fixup` delete & re-clone the repo locally & make the changes again & force overwrite **(+)** the changes & the will be reflected in github.

For the time being just make a commit for the `sed` compatibility. There seems little point putting the GLOBAL variables into a `case` statement if they will later be split out into a configuration file (so the helper scripts can also be versioned & updated). If you are packaging the bot blocker for FreeBSD you could just include a FreeBSD compatible `cron` file & / or patch the GLOBAL variables

**Comment by netchild** [comment]
Your pidof example is on purpose made to clash with something else/unrelated.

I submitted another request for GNU-sed only. I will also add another pull request (later) to not update the binaries (optional): Stuff installed by the FreeBSD package mangement shall not be modified (I would prefer to change the default setting for this option in FreeBSD instead of removing it completely, additionally this has the benefit that the user interface of the script is the same for those people which use several OS).

**Pull request closed without merging**
