### PR TITLE
Remove false positive of legitimate Real Estate office in Wisconsin

### PR DESCRIPTION
**Pull request by lukeb**

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Merged

If it re-appears on this list then you need to investigate how referral spam is coming from the web site.

**Comment by lukeb** [comment]
Can you describe the previous referral spam? What were the circumstances that caused it to be put on this list?

**Comment by mitchellkrogza** [comment]
@lukeb unfortunately that was in a very early commit and the http logs of that time period are no longer accessible. A grep through the last 12 months of logs does not show any reference to the domain so quite possible somebody was spoofing the referrer strings.

**Comment by lukeb** [comment]
Ok, thanks for looking into it. This is a very popular real estate website in Wisconsin. They do get a lot of traffic and they write a lot of articles and blogs. Referral traffic may be normal and natural. Not sure what sites your logs were from.

**Comment by mitchellkrogza** [comment]
Thanks for reporting it, sadly false positives can and do occur. 

I did find the log file in question on a backup and it was from my environmental web site which accepts guest submissions, have they ever written any environmental guest blogs? 

I cannot trace their domain in any posts on the site but will do a search in mySQL to confirm.

**Pull request merged**
