### PR TITLE
setup-ngxblocker / install-ngxblocker fixes

### PR DESCRIPTION
**Pull request by itoffshore**
* `install-ngxblocker`: don't use `grep -q` or `&>/dev/null` (they are **not** portable)
* `include_filelist.txt`: add `$VHOST_INCLUDES`
* `setup-ngxblocker`: add `check_wildcard()` fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/43

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Spot on @itoffshore tested and passed 100%. Great work you have done on this. Thank you so much.

I will be updating readme and configuration files to use the install-ngxblocker and setup-ngxblocker methods and have a separate readme for those wanting manual configuration instructions.

Once done with above, I will make TravisCI do all it's tests from now on using your install, setup and update scripts as it's preferred method of installation and testing.

**Comment by mitchellkrogza** [comment]
@itoffshore 

setup-ngxblocker is still adding

```
include /etc/nginx/conf.d/globalblacklist.conf;
include /etc/nginx/con.d/botblocker-nginx-settings.conf;
```

into /etc/nginx.conf file

Not needed as it is already loaded into nginx with the default include in nginx.conf `include /etc/nginx/conf.d/*;` this causes double loading of both globalblacklist.conf and botblocker-nginx-settings.conf causing Nginx EMERG errors.

Also within TravisCI testing environment I get an error running the setup-ngxblocker .... it runs and does the includes OK but gives an error `sed: -e expression #1, char 3: unexpected `,'`

If we can get this duplication of includes fixed in setup-ngxblocker then I can bring the new Travis tests online fully.

**Comment by itoffshore** [comment]
@mitchellkrogza - I don't get any errors in an `lxc` container with ubuntu `16.04`

which version of `sed` &  `/bin/sh` are in travis ?

**Comment by mitchellkrogza** [comment]
@itoffshore Travis CI runs on Trust Builds, new setup-ngxblocker

`sed` (GNU sed) 4.2.2

```
dash:
Installed: 0.5.7-4ubuntu1
Candidate: 0.5.7-4ubuntu1
Version table: *** 0.5.7-4ubuntu1 0
```

The new version of the setup script runs and now detects the wildcard and does not do the additional includes but still throws an error

```
sed: -e expression #1, char 3: unexpected `,'

INFO:      /etc/nginx/conf.d/* detected                 => /etc/nginx/nginx.conf
```

**Comment by mitchellkrogza** [comment]
Travis also prints this at part of it's Build System Information:

```
bash version

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

**Pull request merged**
