### PR TITLE
update-ngxblocker: add -b (bot.d directory) option

### PR DESCRIPTION
**Pull request by itoffshore**
it is not currently possible to set a variable at the `http{}` level to use in `nginx` include files.

adds `-b` option / `$BOTS_DIR` variable to `update-ngxblocker` for custom `bots.d` locations

closes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/68

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore great work 👍

**Comment by mitchellkrogza** [comment]
@itoffshore I will integrate a second round of testing in Travis CI after test 1 passes using default nginx locations. 

This second test will use install, setup and update scripts using a non-standard location so that Travis CI can test this as part of it's build process too. 👍

**Comment by mitchellkrogza** [comment]
@itoffshore and here we go. Travis CI now runs a second round of tests using your scripts and a non-standard folder location of `/usr/local/nginx/bots.d` and `/usr/local/nginx/conf.d` and then runs a second round of curl_tests before deploying. 

Thanks to you, I never though of adding additional tests like this to use the command line switches of the scripts and it works 100%. So now all future testing will test your scripts even better than before 👍 

https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/257252208

**Comment by itoffshore** [comment]
I'll have a look later today at implementing a [file check for `update-ngxblocker`](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/33#issuecomment-313470555) too

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore much appreciated 🥇  Going from strength to strength and I truly appreciate your contributions. Now anything you ever modify on your scripts will be much more thoroughly tested by Travis 👍 

I'' do some doc updates to explain this users better.

**Pull request merged**
