### PR TITLE
Various small fixes

### PR DESCRIPTION
**Pull request by itoffshore**
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/83#issuecomment-330304279
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/89#issuecomment-330321557
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/97

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore passed with flying colors > https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/277774830 👍

**Comment by mitchellkrogza** [comment]
@itoffshore would it all be possible to include a function into the update-ngxblocker that calls a php on a web page which can track the IP address, hostname, date and time etc of each download of globalblacklist.conf? I'd like to be able to have some kind of stat tracking for this to monitor active users and downloads of globalblacklist.conf. Unfortunately GITHUB has no way of tracking downloads of individual files only Releases. Can u mull this one over ??

**Comment by itoffshore** [comment]
setup a `php` page somewhere that just accepts a `curl` user agent & I'll add a function that grabs a tiny part of the page

**Comment by mitchellkrogza** [comment]
Awesome @itoffshore I’ll get that done and send you the link tomorrow. :+1:

**Comment by mitchellkrogza** [comment]
@itoffshore sorry this slipped my mind, I set up a basic site with an index.html that accepts a curl request. Does it have to be a php page? Have a look `curl -I https://ngxbbb.ubuntu101.co.za`

**Pull request merged**
