### PR TITLE
Use full path for curl (cron).

### PR DESCRIPTION
**Pull request by netchild**
In case curl is not in path of cron (I stumbled over it on a system).

### CODE REVIEW

**Comment by netchild** [comment]
I get conflicts when I try to rebase this.
Is it OK like this or shall I create a new branch and apply the diff for CURL_PATH?

**Comment by itoffshore** [comment]
I would:

- copy your locally changed files somewhere
- delete the local git branch
- update the local master & `checkout` a new local branch with the same name
- copy the changed files over & check the changes with `git diff`
- make a commit & force overwrite the remote branch

**Comment by netchild** [comment]
Done as requested.

That's a workflow which works (and is easy) for small changes like this, but for big changes (e.g. for kernel development where you touch tens or hundreds of files) this is a nightmare. Do you have by chance a pointer to docs how to handle this better for bigger changes?

**Comment by itoffshore** [comment]
@netchild  - I have [some notes here for PR's on Github](https://it-offshore.co.uk/code/81-alpine-linux-pull-requests-on-github)

I only do a merge on `master` never on the local branch I'm working on. I find on merge conflicts it is simpler to delete & re-create the local branch as noted above

**Pull request merged**
