### PR TITLE
update-ngxblocker: add command line switches

### PR DESCRIPTION
**Pull request by itoffshore**
* adds help menu & command line switches
* to view options run:

`update-ngxblocker -h`

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
@itoffshore is there a possibility you can make the update-ngxblocker also check for the existence of all required include files BOT_FILES and CONF_FILES specified in the include_filelist.txt as part of it's update. In the case a user deleted a required include it would fail reloading Nginx. 

Would also help future proof against failures for any future version updates that may introduce a new required include file as it would then pull the new (or missing) file when it see's a new file in the include_filelist.txt.

**Comment by itoffshore** [comment]
ok - I'll have a think about how best to implement it.

**Comment by mitchellkrogza** [comment]
Look forward to it, I think it will be a great new feature

**Comment by itoffshore** [comment]
see https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/71

**Pull request merged**
