### PR TITLE
setup-ngxblocker: fix sed error in Travis

### PR DESCRIPTION
**Pull request by itoffshore**
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/45

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Tested this morning still getting the same error on Travis.

```
sed: -e expression #1, char 3: unexpected `,'
INFO:      /etc/nginx/conf.d/* detected                 => /etc/nginx/nginx.conf
```

I ran it again inside travis with `sh -x setup-ngxblocker` and it happens in this section of the script

```
find_line /etc/nginx/sites-available/default.vhost location first

+ local file=/etc/nginx/sites-available/default.vhost find_str=location first_last=first

+ awk /location/{ print NR; exit } /etc/nginx/sites-available/default.vhost

+ local end=

+ sed -n 5,p /etc/nginx/sites-available/default.vhost

sed: -e expression #1, char 3: unexpected `,'

+ find_line /tmp/tmp.2Ytft8iCCE include last

+ local file=/tmp/tmp.2Ytft8iCCE find_str=include first_last=last

+ + tail -n1
```

**Comment by itoffshore** [comment]
@mitchellkrogza - can you put the contents of `/etc/nginx/sites-available/default.vhost` on https://hastebin.com/ please - it seems to be failing due to no `location` block.

**Comment by mitchellkrogza** [comment]
Never used hastebin but hope this works. https://hastebin.com/hinorawofi.nginx

Otherwise here it is below, very basic vhost file for testing in Travis.

```
server {
	listen *:9000;

	root /var/www/html;
	server_name localhost;
	charset UTF-8;

		# Block Bad Bots
		include /etc/nginx/bots.d/blockbots.conf;
		include /etc/nginx/bots.d/ddos.conf;
}
```

**Comment by mitchellkrogza** [comment]
Silly me, I put such a simple vhost file for testing I didn't add any location {} section. Duh. I will modify that vhost file now and run a test on Travis to confirm it fixes that error.

Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license

**Comment by mitchellkrogza** [comment]
Confirmed fixed and working 100% on Travis CI, was the missing location {} directive in the .vhost file. Change it to this below and it passed without that sed error. https://hastebin.com/enimewovof.nginx

Silly me ... now I can bring the TravisCI testing into the live repo tomorrow.
Passes all tests on my Nginx playground repo
https://travis-ci.org/mitchellkrogza/Travis-CI-Nginx-for-Testing-Nginx-Configuration/builds/228405537

PLEASE don;t go look through my extremely messy code in that test repo 😬

**Comment by itoffshore** [comment]
will make a small change to `setup-ngxblocker` anyway - it is still a bug

**Pull request merged**
