### PR TITLE
Remove archive.org_bot bad-user-agents.list 

### PR DESCRIPTION
**Pull request by MaximeMichaud**
https://archive.org/details%2Farchive.org_bot%2F
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/183

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
You can whitelist it yourself in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/bots.d/blacklist-user-agents.conf (both white & blacklist) it will remain blocked unfortunately unless you whitelist it yoursefl.

**Comment by MaximeMichaud** [comment]
So, I will Whitelist archive.org on hundred of host.
Unfortunately.

**Comment by mitchellkrogza** [comment]
Never had a complaint yet in all these years and this blocker was built for my own needs and then made pubic. Most site owners do not want their site crawled by archive.org. It should take you all of 2 minutes with the command line to roll out a customized version of the whitelist file to thousands of sites. Sorry but it remains as is.

**Comment by MaximeMichaud** [comment]
I was not asking for any modification after the pull was closed :)
Nevertheless, I am not the only one that may think that archive.org should not be blocked.

**Pull request closed without merging**
