### PR TITLE
setup-ngxblocker: fix sed error / refactor $col_size

### PR DESCRIPTION
**Pull request by itoffshore**
fixes https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/47

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore will do final tests tomorrow before bringing the new Travis testing into place using the setup, install and update scripts as part of the Travis build tests


Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license

**Comment by itoffshore** [comment]
the tests look great well done - hopefully this was the last bug `;o)`

**Comment by mitchellkrogza** [comment]
Latest fix to setup-ngxblocker once again misses the wildcard in nginx.conf and does the includes, from TravisCI log this morning

```
+sudo ./setup-ngxblocker -x

Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt
INFO:      /etc/nginx/conf.d/* detected               => /etc/nginx/nginx.conf
inserting: include /etc/nginx/bots.d/blockbots.conf;  => /etc/nginx/sites-available/default.vhost
inserting: include /etc/nginx/bots.d/ddos.conf;       => /etc/nginx/sites-available/default.vhost
```

**Comment by itoffshore** [comment]
The above is detecting the wildcard correctly  in `nginx.conf` (which is why it is `INFO` not `inserting:`)

It is only making inserts to `default.vhost` for the bot files.

**Comment by mitchellkrogza** [comment]
Ahh, gotya @itoffshore 👍  .... sorry for my oversight. My eyes are so screwed from messing with Travis for an entire week. All scripts install, setup and update are now passing all Travis tests with flying colors. Now to move these new tests into the live repo 😀 Thank you for all your hard work and excellent scripts. Hope to have all new Travis testing and doc updates in the live repo by tomorrow latest.

**Comment by mitchellkrogza** [comment]
@itoffshore 400 builds and finished with final testing - see https://travis-ci.org/mitchellkrogza/Travis-CI-Nginx-for-Testing-Nginx-Configuration/builds/228713617

Pure Magic !!! 👍

**Pull request merged**
